language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - python manage.py db upgrade
# command to run tests
script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - python -m unittest
